name: Aktualizuj plan zajec

on:
  workflow_dispatch:        # reczne uruchomienie przyciskiem
  schedule:
    - cron: '0 6,15,21 * * *'  # Uruchamia się 3 razy dziennie
  push:
    branches: [main]
    paths: ["main.py", "requirements.txt"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Generuj plik ICS
        env:
          INDEX_NUMBER: ${{ secrets.INDEX_NUMBER }}
        run: python main.py

      - name: Commit wynikow
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add plan_zajec_IOSI.ics pobrany_plan.xlsx
          git commit -m "Aktualizacja planu" || echo "Brak zmian"
          git push
